# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: __default

  jobs:
  - job: Job
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Tests_High: 
          TestsPriority: "High"
        Tests_Medium:
          TestsPriority: "Medium"
        Tests_Low:
          TestsPriority: "Low"

      maxParallel: 3 
  
    variables:
        - group: GlobalVariables

    steps:
    - task: Bash@3
      displayName: 'Create Java test image'
      inputs:
        targetType: 'inline'
        script: 'docker build -t seleniumtests .'
        
    - task: Bash@3
      displayName: 'Run Java test container'
      inputs:
        targetType: 'inline'
        script: 'docker run -e "BROWSER=chrome" --name tests seleniumtests'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'export BROWSER=$(BROWSER)'
    - task: Maven@3

      inputs:

        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'clean test -Dgroups=$(TestsPriority)'
        
    - task: Bash@3
      displayName: "display files from project folder"
      inputs:
        targetType: 'inline'
        script: 'ls $(System.DefaultWorkingDirectory)'
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Log File as Artifact'
      condition: always()
      inputs:         
          PathtoPublish: $(System.DefaultWorkingDirectory)/target/logs
          ArtifactName: logs
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Screenshot File as Artifact'
      condition: always()
      inputs:         
          PathtoPublish: $(System.DefaultWorkingDirectory)/target/screenshots
          ArtifactName: logs
